#!/bin/bash

echo
echo "=== Stopping old container ==="
echo

distrobox stop dterm

echo
echo "=== Cleaning up ==="
echo

cd $HOME/distrobox
sudo rm -rf dterm
distrobox rm dterm

echo
echo "=== Getting latest image ==="
echo

podman pull ghcr.io/davemccrea/dterm:latest

echo
echo "=== Starting up new container ==="
echo

distrobox create --yes --image ghcr.io/davemccrea/dterm:latest --name dterm --home ~/distrobox/dterm
distrobox enter dterm -- ' sh /bootstrap.sh'

echo
echo "Done!"
