#!/bin/bash

echo
echo "=== Stopping old container ==="
echo

distrobox stop boxkit

echo
echo "=== Cleaning up ==="
echo

sudo rm -rf /var/home/$USER/distrobox/boxkit
distrobox rm boxkit

echo
echo "=== Getting latest image ==="
echo

podman pull ghcr.io/davemccrea/boxkit:latest

echo
echo "=== Starting up new container ==="
echo

distrobox create --yes --image ghcr.io/davemccrea/boxkit:latest --name boxkit --home ~/distrobox/boxkit
distrobox enter boxkit -- ' sh /bootstrap.sh'

echo
echo "Done!"
